// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: services.proto
#ifndef GRPC_services_2eproto__INCLUDED
#define GRPC_services_2eproto__INCLUDED

#include "services.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace solver {

class Calculate final {
 public:
  static constexpr char const* service_full_name() {
    return "solver.Calculate";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends an expression to calculate
    virtual ::grpc::Status Evaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::solver::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>> AsyncEvaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>>(AsyncEvaluateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>> PrepareAsyncEvaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>>(PrepareAsyncEvaluateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends an expression to calculate
      virtual void Evaluate(::grpc::ClientContext* context, const ::solver::Expression* request, ::solver::Result* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>* AsyncEvaluateRaw(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::solver::Result>* PrepareAsyncEvaluateRaw(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Evaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::solver::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::solver::Result>> AsyncEvaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::solver::Result>>(AsyncEvaluateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::solver::Result>> PrepareAsyncEvaluate(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::solver::Result>>(PrepareAsyncEvaluateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Evaluate(::grpc::ClientContext* context, const ::solver::Expression* request, ::solver::Result* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::solver::Result>* AsyncEvaluateRaw(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::solver::Result>* PrepareAsyncEvaluateRaw(::grpc::ClientContext* context, const ::solver::Expression& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Evaluate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends an expression to calculate
    virtual ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Evaluate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEvaluate(::grpc::ServerContext* context, ::solver::Expression* request, ::grpc::ServerAsyncResponseWriter< ::solver::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Evaluate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Evaluate() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::solver::Expression, ::solver::Result>(
          [this](::grpc::ServerContext* context,
                 const ::solver::Expression* request,
                 ::solver::Result* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Evaluate(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Evaluate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Evaluate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Evaluate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEvaluate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Evaluate() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Evaluate(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Evaluate(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Evaluate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Evaluate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::solver::Expression, ::solver::Result>(std::bind(&WithStreamedUnaryMethod_Evaluate<BaseClass>::StreamedEvaluate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Evaluate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Evaluate(::grpc::ServerContext* context, const ::solver::Expression* request, ::solver::Result* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEvaluate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::solver::Expression,::solver::Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Evaluate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Evaluate<Service > StreamedService;
};

}  // namespace solver


#endif  // GRPC_services_2eproto__INCLUDED
